services:
  - type: web
    name: bustrack-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://bustrack-be165.web.app
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: ADMIN_API_SECRET
        sync: false
